before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - bin/setup
branches:
  only:
    - master
cache:
  - bundler
language:
  - ruby
notifications:
  email: false
rvm:
  - 2.3.1
addons:
  postgresql: "9.3"
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: WmB1thnYD6EsqLkWB4t580YDzHL/tkLOBFkBckkaoLKMouv95JY7scK9snSNF4XMJPAk9h3yrx0MBC3GK1trvoxAfQjwF3bw8AKtFFPUjAf4iuJPp1pcz6b7uYu39kQlDPXWDNfLq7nzCaW8meKGyDgTjpsLA0qvVACj0STkmXg=
  app: railsbridge-boston-staging
