name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.1
    - name: Install dependencies
      run: bundle install
    - name: Copy sample ENV vars
      run: cp .sample.env .env
    - name: Run tests
      run: bundle exec rake
